services:
  clamav:
    container_name: clamav
    image: clamav/clamav
    platform: linux/amd64
    environment:
      - NODE_ENV=${NODE_ENV}
    ports:
      - "3310:3310"
    volumes:
      - ./config/clamd.conf:/etc/clamav/clamd.conf
      - ./config/freshclam.conf:/etc/clamav/freshclam.conf
      - ./data/clamav:/var/lib/clamav
      - ./logs:/var/log/clamav
    command: ["sh", "-c", "freshclam && clamd"]
    healthcheck:
      test: ["CMD", "clamdscan", "--version"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always
    networks:
      - malware-scanner-network

  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-app
    environment:
      - NODE_ENV=${NODE_ENV}
      - CLAMAV_HOST=clamav
      - CLAMAV_PORT=3310
    ports:
      - "3001:3001"
    volumes:
      - ./:/app
      - /app/node_modules
      - /tmp/clamav-scans:/tmp/clamav-scans
    depends_on:
      clamav:
        condition: service_healthy
    restart: always
    networks:
      - malware-scanner-network

  mailhog:
    container_name: mailhog
    image: mailhog/mailhog:latest
    platform: linux/amd64
    environment:
      - NODE_ENV=${NODE_ENV}
      - MAILHOG_SMTP_PORT=${MAILHOG_SMTP_PORT}
      - MAILHOG_HTTP_PORT=${MAILHOG_HTTP_PORT}
      - DEV_SMTP_HOST=${DEV_SMTP_HOST}
      - DEV_FROM_EMAIL=${DEV_FROM_EMAIL}
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - malware-scanner-network

networks:
  malware-scanner-network:
    name: malware-scanner-network